services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: engineerbrain-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: engineerbrain
      RABBITMQ_DEFAULT_PASS: engineerbrain
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
